# Generated by Django 3.1.7 on 2021-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-title']},
        ),
    ]
